### ISSUE TITLE
Vertical panel

### ISSUE THREAD

**Issue by MatejSpindler** [bouteillerAlan/archupdate#2] opened 2022-11-22 15:49 UTC
### Version

v3.1-beta

### What steps will reproduce the bug?

Change to vertical panel.

Add widget.

### What do you see instead?

If the panel is in vertical orientation, the icon is not the correct size.

![Vertical panel](https://user-images.githubusercontent.com/1609645/203355301-dca3d906-6a4e-4ca8-9f2c-e352a747736d.png)

**Comment by bouteillerAlan** [comment] 2022-11-22 22:15
Hello, I have merged a fix for this issue. 

The pling site is down, so I will update the package tomorrow morning on it.
While waiting for me to take care of pling the new version is available on [github](https://github.com/bouteillerAlan/archupdate/releases/download/v3.2-beta/a2n.archupdate.3.2-beta.tar.gz) :)

Don't hesitate to update the widget and re-open an issue if the problem is still there.

**Closed by bouteillerAlan** 2022-11-22 22:15 UTC
Labels: bug
